name: Build on Ubuntu

on: [push, pull_request]

jobs:
  build_qt:
    name: With QT GUI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install packages on Ubuntu 20.04
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install build-essential qt5-default libqt5gui5 libboost1.74-dev libminiupnpc-dev libssl-dev zlib1g-dev
    - name: Install packages on Ubuntu 22.04
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install build-essential qtbase5-dev qt5-qmake libqt5gui5 libboost-all-dev libminiupnpc-dev libssl-dev zlib1g-dev
    - name: Build application
      run: |
        qmake
        make -j$(nproc)
